baseurl = "http://npf.io/tod/"
languageCode = "en-us"
title = "Tyranny of Dragons"
theme = "hyde"
copyright = "Nate Finch"

[Author]
	name = "Nate Finch"

[permalinks]
	adventure-log = "/adventure-log/:year/:month/:day/:filename/"

[taxonomies]


[params]
	description = "A 5th Edition D&D Campaign"
